/** Vocabulário odontológico PT-BR para batch STT e keyterms do streaming AssemblyAI (máx. 100 termos). */
export const DENTAL_VOCABULARY_PT_BR = [
  // Anatomia dental
  "gengiva",
  "dentina",
  "esmalte dentário",
  "polpa dentária",
  "câmara pulpar",
  "raiz dentária",
  "ápice radicular",
  "alvéolo",
  "ligamento periodontal",
  "cemento",
  "furca",
  // Patologias e diagnósticos
  "cárie",
  "periodontite",
  "gengivite",
  "bruxismo",
  "halitose",
  "maloclusão",
  "mordida aberta",
  "mordida cruzada",
  "sobremordida",
  "protrusão",
  "retração gengival",
  "infecção odontogênica",
  // Procedimentos clínicos
  "extirpação pulpar",
  "endodontia",
  "retratamento",
  "canal radicular",
  "obturação",
  "exodontia",
  "extração dentária",
  "alveoloplastia",
  "profilaxia",
  "raspagem",
  "alisamento radicular",
  "curetagem",
  "polimento dental",
  "gengivoplastia",
  "cirurgia",
  "retalho cirúrgico",
  "sutura",
  // Implantodontia e cirurgia
  "implante dentário",
  "osseointegração",
  "enxerto ósseo",
  "membrana reabsorvível",
  "regeneração óssea guiada",
  "sinuslift",
  // Prótese e restauração
  "prótese dentária",
  "coroa dentária",
  "faceta de porcelana",
  "restauração",
  "amálgama",
  "resina composta",
  "ionômero de vidro",
  // Estética e ortodontia
  "clareamento dental",
  "ortodontia",
  "aparelho ortodôntico",
  "Invisalign",
  "contenção",
  // Prevenção
  "flúor",
  "selante",
  // Oclusão e ATM
  "oclusão",
  "plano oclusal",
  "ATM",
  "articulação temporomandibular",
  "disfunção temporomandibular",
  "bifurcação",
  "trifurcação",
  // Exames de imagem
  "radiografia",
  "rx panorâmico",
  "tomografia cone beam",
  "periapical",
  // Anestesia e medicamentos
  "anestesia local",
  "lidocaína",
  "articaína",
  "amoxicilina",
  "azitromicina",
  "metronidazol",
  "ibuprofeno",
  "paracetamol",
  "dipirona",
  "anti-inflamatório",
  "analgésico",
  "antibiótico",
  // Consulta e fluxo clínico
  "prescrição",
  "receita médica",
  "consulta odontológica",
  "consulta de retorno",
  "odontograma",
  "periodontia",
  "dente do siso",
  "cicatrização",
  "curativo cirúrgico",
  "fio de sutura",
] as const;

export const ASSEMBLYAI_STREAMING_KEYTERMS = DENTAL_VOCABULARY_PT_BR.slice(0, 100);
