/** Vocabulário odontológico PT-BR para batch STT e keyterms do streaming AssemblyAI (máx. 100 termos). */
export const DENTAL_VOCABULARY_PT_BR = [
  "bruxismo",
  "ATM",
  "periodontite",
  "endodontia",
  "gengivite",
  "oclusão",
  "retratamento",
  "implante",
  "prótese",
  "canal",
  "exodontia",
  "clareamento",
  "faceta",
  "Invisalign",
  "aparelho",
  "contenção",
  "radiografia",
  "tomografia",
  "cirurgia",
  "anestesia",
  "lidocaína",
  "articaína",
  "profilaxia",
  "raspagem",
  "curetagem",
  "enxerto",
  "consulta odontológica",
  "odontograma",
  "ortodontia",
  "periodontia",
] as const;

export const ASSEMBLYAI_STREAMING_KEYTERMS = DENTAL_VOCABULARY_PT_BR.slice(0, 100);
